# Generated by Django 5.0 on 2023-12-28 19:03

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import xwcs.base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lessonpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('h5p_module', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255)), ('h5p_module', wagtail.documents.blocks.DocumentChooserBlock(xwcs.base.models.H5PModule))]))], use_json_field=True),
        ),
    ]
