# Generated by Django 5.0 on 2023-12-28 20:42

import wagtail.blocks
import wagtail.fields
import xwcs.base.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lessonpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('h5p_module', xwcs.base.blocks.H5PChooserBlock())], use_json_field=True),
        ),
    ]
