# Generated by Django 5.0 on 2023-12-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_h5pmodulefile_h5pmodule_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h5pmodule',
            name='h5p_file',
            field=models.FileField(upload_to='h5p', verbose_name='H5P module'),
        ),
        migrations.DeleteModel(
            name='H5PModuleFile',
        ),
    ]
