# Generated by Django 5.0 on 2023-12-28 20:03

import django.db.models.deletion
import taggit.managers
import wagtail.models.collections
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_h5pmodule_h5p_file_delete_h5pmodulefile'),
        ('taggit', '0005_auto_20220424_2025'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='h5pmodule',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='h5pmodule',
            name='file',
        ),
        migrations.RemoveField(
            model_name='h5pmodule',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='h5pmodule',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='h5pmodule',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='h5pmodule',
            name='uploaded_by_user',
        ),
        migrations.CreateModel(
            name='H5PFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to='h5p', verbose_name='H5P file')),
                ('collection', models.ForeignKey(default=wagtail.models.collections.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AlterField(
            model_name='h5pmodule',
            name='h5p_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.h5pfile'),
        ),
    ]
